batch_size = 1024
codepoint_set = "kanji"
epoch_end = 100000
font = "/usr/share/fonts/OTF/ipaexm.ttf"
font_index = 0
unit = 10
density_quantile_min = 0.025
density_quantile_max = 0.975
dataset_random_seed = 0
